export const metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-16 text-[#374151]">
      <h1 className="text-3xl font-black tracking-tight mb-2">Terms of Service</h1>
      <p className="text-sm text-[#9CA3AF] mb-10">Last updated: June 2026</p>

      <section className="mb-8">
        <h2 className="text-lg font-bold mb-3">The service</h2>
        <p className="text-sm leading-relaxed text-[#6B7280]">
          AniDeck provides AI-generated anime tools (Anime Roast, Verdict Engine, Character Match) for entertainment purposes. By using AniDeck you agree to these terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-bold mb-3">AI-generated content</h2>
        <p className="text-sm leading-relaxed text-[#6B7280]">
          All roasts, verdicts, and character match results are generated by Claude AI (Anthropic). They are <strong>for entertainment only</strong> and do not constitute professional reviews, opinions, or factual claims. AI outputs can be wrong, biased, or nonsensical — treat them as such.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-bold mb-3">Acceptable use</h2>
        <ul className="text-sm text-[#6B7280] space-y-2 list-disc pl-5">
          <li>Do not attempt to abuse, circumvent, or stress-test our rate limits.</li>
          <li>Do not use AniDeck to generate content intended to harass or defame individuals.</li>
          <li>Only roast MyAnimeList profiles you own or have explicit permission to roast.</li>
          <li>Do not attempt to inject adversarial prompts into our AI inputs.</li>
          <li>Automated or scripted use of the AI endpoints is not permitted.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-bold mb-3">Disclaimers</h2>
        <ul className="text-sm text-[#6B7280] space-y-2 list-disc pl-5">
          <li>AniDeck is provided <strong>&quot;as is&quot;</strong> without warranty of any kind, express or implied.</li>
          <li>We are not responsible for the content of AI-generated outputs.</li>
          <li>We are not liable for any damages arising from use of this service.</li>
          <li>The service may be unavailable, rate-limited, or discontinued at any time.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-bold mb-3">Affiliate links</h2>
        <p className="text-sm leading-relaxed text-[#6B7280]">
          AniDeck contains affiliate links to Crunchyroll and NordVPN. We earn a small commission at no cost to you if you purchase through these links. We only link to services relevant to anime watching.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-bold mb-3">Third-party content</h2>
        <p className="text-sm leading-relaxed text-[#6B7280]">
          AniDeck is not affiliated with, endorsed by, or sponsored by MyAnimeList, Crunchyroll, NordVPN, Anthropic, or any anime studio or publisher. Anime titles, character names, and related trademarks are the property of their respective owners.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-bold mb-3">Changes</h2>
        <p className="text-sm leading-relaxed text-[#6B7280]">
          We may update these terms. Continued use after updates constitutes acceptance of the new terms. Material changes will update the &quot;Last updated&quot; date above.
        </p>
      </section>
    </div>
  );
}
